# Generated by Django 6.0.2 on 2026-02-07 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modele.person')),
                ('hire_date', models.DateField(null=True)),
                ('bio', models.TextField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contract_type', models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], max_length=5, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('modele.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='modele.instructor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
