# Generated by Django 6.0.1 on 2026-02-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tag_author_tags_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
