# Generated by Django 6.0.2 on 2026-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_options_remove_news_date_of_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='authors', to='news.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.tag'),
        ),
    ]
