# Generated by Django 6.0.2 on 2026-02-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_author_tags_alter_news_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='date_of_publication',
        ),
    ]
